-- GENERATED by /build backend. Compiled SQL per widget per test user, for review. Never executed from here.
-- w1 · kpi.casa_balance · user test.branch.a (branch_manager → by_entitlement: DXB01)
SELECT SUM(balance_amount) AS value
FROM   bi_model.v_balances_daily
WHERE  snapshot_date = :last_business_day
  AND  product_family = 'CASA' AND account_status <> 'D'
  AND  branch_code IN (:v1);

-- w1 · kpi.casa_balance · user test.hq (head_office → all)
SELECT SUM(balance_amount) AS value
FROM   bi_model.v_balances_daily
WHERE  snapshot_date = :last_business_day
  AND  product_family = 'CASA' AND account_status <> 'D';

-- w3 · kpi.casa_balance by customer_segment · user test.branch.b (by_entitlement: DXB07, DXB09)
SELECT customer_segment, SUM(balance_amount) AS value
FROM   bi_model.v_balances_daily
WHERE  snapshot_date = :last_business_day
  AND  product_family = 'CASA' AND account_status <> 'D'
  AND  branch_code IN (:v1, :v2)
GROUP  BY customer_segment
ORDER  BY value DESC;

-- w1 · kpi.casa_balance · user test.none (no role → default none)
SELECT SUM(balance_amount) AS value
FROM   bi_model.v_balances_daily
WHERE  snapshot_date = :last_business_day
  AND  product_family = 'CASA' AND account_status <> 'D'
  AND  1 = 0;
